# Generated by Django 3.0.2 on 2020-05-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200505_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='images/profiles/user-blank-image.png', upload_to='images/profiles/'),
        ),
    ]
