# Generated by Django 3.0.2 on 2020-05-13 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_request_user'),
        ('application', '0002_request_accepted'),
    ]

    operations = [
    ]
