# Generated by Django 3.0.2 on 2020-05-05 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200505_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account_confirmed',
            new_name='confirmed',
        ),
    ]
