# Generated by Django 3.0.2 on 2020-05-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20200505_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='150', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='150', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='images/profiles/user-blank-image.png', height_field='image_height', help_text='Profile Picture', upload_to='images/profiles/', verbose_name='Profile Picture', width_field='image_width'),
        ),
    ]
